import type { NextPage } from 'next'
import Head from 'next/head'
import html2canvas from 'html2canvas'
import jspdf from 'jspdf'
import { useState } from 'react';
// import logo from 'assets/LogoDark.svg'

function GerarPDF() {

  html2canvas(document.getElementById('data')).then(function (canvas) {
    const doc = new jspdf({
      orientation: "portrait", unit: "mm",
    });
    const img = 'assets/LogoDark.png'

    doc.setFont("helvetica")
    doc.setFontSize(11)
    doc.addImage(canvas, 'JPEG', 10, 10, 0, 0)
    // doc.addImage(img, 'JPEG', 10, 10, 0, 0)
    doc.save("TestePDF.pdf");
  });
}


const Home: NextPage = () => {


  return (
    <><Head>
      <title>Gerar PFF</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
      <div id="data">
        <h1>Teste - api html2pdf.js:</h1>
        <table className="table table-dark">
          <thead>
            <tr>
              <th>Firstname</th>
              <th>Lastname</th>
              <th>Email</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>John</td>
              <td>Doe</td>
              <td>john@example.com</td>
            </tr>
            <tr>
              <td>Mary</td>
              <td>Moe</td>
              <td>mary@example.com</td>
            </tr>
            <tr>
              <td>July</td>
              <td>Dooley</td>
              <td>july@example.com</td>
            </tr>
          </tbody>
        </table>
      </div>
      <button type="button" id="print " onClick={() => GerarPDF()}>Gerar PDF</button>
    </>
  )
}
export default Home;
